# See latest at https://fabricmc.net/develop/
deps.minecraft=1.21
deps.yarn_mappings=1.21+build.9
deps.java=17

mod.version_name=1.21

mod.min_target=1.21
mod.max_target=1.22

# TODO: figure out what versions it supports
publishing.supported_versions=1.20.2,1.20.3,1.20.4,1.20.5,1.20.6,1.21,1.21.1,1.21.2,1.21.3,1.21.4