# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#org.gradle.parallel=true

mod.version=2.0.0
mod.name=codelib
mod.maven_group=net.notcoded

mod.version_name=[VERSIONED]

mod.min_target=[VERSIONED]
mod.max_target=[VERSIONED]

publishing.supported_versions=[VERSIONED]

# Dependencies
# https://fabricmc.net/develop
deps.yarn=[VERSIONED]
deps.fabric_loader=0.14.21
deps.errorprone=2.36.0
deps.java=[VERSIONED]

