# See latest at https://fabricmc.net/develop/
deps.minecraft=1.18.2
deps.yarn_mappings=1.18.2+build.4
deps.java=17

mod.version_name=1.18.2

mod.min_target=1.18
mod.max_target=1.18.2

# TODO: figure out what versions it supports
# as it seems 1.17 and 1.18 are compatible
publishing.supported_versions=1.18,1.18.1,1.18.2