name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Temurin 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Publish to modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}